#!/bin/sh

detect_OS() {
    os_name=`uname -s`
    if [[ $os_name == 'Darwin' ]]; then
        os_type='Mac'
    elif [[ $os_name == 'Linux' ]]; then
        os_type='Linux'
    else
        os_type='unknow'
    fi

    echo OS is $os_type
}

detect_OS

homemaker -verbose -task $os_type dotfiles.yaml .
